### ISSUE TITLE
safe mode for npefix

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/npefix#10]
with

* s3 skip statement
* S4a return null
* S4b return new (exp return constant)
* S4c return existing
* S4d return void

**Comment by btellstrom** [comment]
Some further clarification on this issue would be helpful. Do you mean that I am to create a new mode called "safe mode" that ensures all the bullet points? Would that require me to implement some new strategy for searching?

Or am I implementing a flag that when set to true ensures that the strategies do as stated above? If so, I am curious how I would distinguish between S4b and S4c? Would I simply look for the keyword "new"?

**Comment by monperrus** [comment]
It's not implementing a new strategy, it's only discarding some of them.
